INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('USUARIOFO','USUARIOFO','Usuario','imed@imed.com.ar','Usuario para el Front Offices');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('TEST2','admin','Oscarly Graterol','oscarlygraterol@gmail.com','opadmin');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('TEST','.','Usuario de Test','test.imed@siemens.com.ar','Usuario para testing.');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('SUIZO','SUIZO00','Usuario SUIZO para switch','','');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('SSANCH','Inicio00','Sebastian Sanchez Schemberger','sebastian.sanchezschemberger@wordline.com','Arquitecto/Desarrollador');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('SOMERFUG','SOMERFUG00','SOMERFUG','-','User SwitchImed - SOMERFUG');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('SELMA','SELMA00','Usuario SELMA para switch','','');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('SDESK','sdesk','Service Desk IMED','ServiceDesk@siemens.com.ar','Service Desk de Imed');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('RPAEZX','123456','Rodolfo Paez','-','Recepecion-Auditor');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('RGINIX','china2014','RAUL GINIX','','Operador Iemd');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('QC_IMED','QC','Usuario QC para ABI Imed','','Usuario para QC -> IMED');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('QC_FLK','QC','Usuario QC para ABI Farmalink','','Usuario para QC -> FLK');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('OPIMED','imed','Operaciones IMED','imed@siemens.com.ar','Area de Operaciones Imed');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('OPFLKGC','flkgc','Raquel Rizzolli','raquel.rizzolli@farmalink.com.ar','Gerencia clínica');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('OPFLK','farmalink','Operaciones Farmalink','imed@siemens.com.ar','Area de Operaciones Farmalink');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('OPENFARMA','OPENFARMA00','Usuario OpenFarma para switch','','');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('OPADMIN','admin','Administrador Operaciones IMED','imed@siemens.com.ar','Admin de Area de Operaciones Imed');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('OGRATE','123456','Oscarly Graterol','oscarlygraterol@gmail.com','prueba');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('NOCIMED','nocimed00','NOC IMED','','NOC Iemd');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('MONITOR','MONITOR00','Usuario para el monitoreo','','');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('LRAFFI','lraffi','Lisandro Raffioni','Lisandro.Raffioni@atos.net.ar','Op. Imed - Lisandro Raffioni');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('LAUNCHERDUO','LAUNCHERDUO00','Usuario de la aplicacion LacuncherDuo','','');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('LABADMUSER','LabAdmUser00','Administrador del WS Labo','admin.imed@siemens.com.ar','Administrador general de los nuevos servicios de Laboratorio');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('JVILLAX','jvillax','Javier Villa Real','.','Recepcion');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('JVILLA','123456','Javier Villa Real','-','Recepcion');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('JDIAZX','JDIAZX','Javier Diaz','-','Recepcion');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('HBENIX','hbenix','HERNAN DIEGO BENITEZ','hernan.benitez@worldline.com','ADMIN');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('HBENIT','hbenit','Hernan Benitez','hernan.benitez.ext@atos.net.ar','ADMIN');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('GCONTR','gcontr','Gabriela Contrera','Gabriela.Contrera.ext@atos.net.ar','Op. Imed - Gabriela Contrera');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('FLKBATCH','flk123','FLKBATCH','noinformado@noinformado.com.ar','FLKBATCH');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('FFAVRO','ffavro','Federico Favrot','federico.favrot@atos.net.ar','Control Auditoria');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('FCRAVA','fcrava','Fabian Cravaroli','fabian.cravaroli@atos.net.ar','Imed');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('FARMALINK','FARMALINK00','Usuario general para Farmalink','','');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('FACAF','FACAF00','Usuario de la aplicacion LacuncherDuo para Facaf','','');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('EDENADMIN','edenadmin00','Administrador Edenred','prueba01@imed.com','Administrador general de Edenred');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('ECACER','123456','Martin Caceres','-','Recpecion');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('CCBAPRO','bapro','Usuario Call Center BAPRO','CallCenter@bapro.com.ar','Area Call Center de BAPRO');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('CCARAB','123456','Carlos Carabajal','-','Recepcion');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('CC000003','12345678','Licha Prueba','addad','Operador Bapro');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('CC000002','123789','PREUBA02','prueba@imed.com','PRUEBA LARGA 02');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('CALLCENTER','callcenter','Call Center','Sandra.Sosa@atos.net.ar','Help Desk - Call Center Imed');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('CALL','center','Usuario Call Center IMED','CallCenter@siemens.com.ar','Area Call Center de Imed Imed');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('BO','BO00','Usuario del BO para transaccionar con el SwitchImed','','');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('AUTWEB','AUTWEB00','Usuario del AUTWEB para transaccionar con el SwitchImed','','');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('ASOFAR','ASOFAR00','Usuario de la aplicacion LacuncherDuo para Asofar','','');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('AGV','AGV123','Usuario Agente Virtual','imed@imed.com.ar','Usuario para las consultas del Agente Virtual');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('ADMIN','Inicio','Administrador General','admin.imed@siemens.com.ar','Administrador general de los sistemas');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('ACHAGA','ACHAGA','Andres Chagas','Andres.Chagas.ext@atos.net.ar','Operador de Auditoria');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('AACUNA','123456','Alejandro Acuna','-','Recepcion');
INSERT INTO fwim_user (userid,userpass,username,useremail,userdescri) VALUES ('70000136005','9999','FARMALINK','',null);

alter table fwim_user add column userrole varchar(10) not null default "User";

